executable     = /eos/home-t/theofil/work/akcolor/makefriends/C/summer26/NNFullRaw/infer_gpu.sh
output         = /eos/home-t/theofil/work/akcolor/makefriends/C/summer26/NNFullRaw/logs/infer_gpu.$(ClusterId).out
error          = /eos/home-t/theofil/work/akcolor/makefriends/C/summer26/NNFullRaw/logs/infer_gpu.$(ClusterId).err
log            = /eos/home-t/theofil/work/akcolor/makefriends/C/summer26/NNFullRaw/logs/infer_gpu.$(ClusterId).log

request_cpus   = 2
request_memory = 8GB
request_gpus   = 1

+JobFlavour    = "microcentury"

queue
