executable     = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/deepsets/train_gpu.sh
output         = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/deepsets/logs/train.$(ClusterId).out
error          = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/deepsets/logs/train.$(ClusterId).err
log            = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/deepsets/logs/train.$(ClusterId).log

request_cpus   = 2
request_memory = 8GB
request_gpus   = 1

+JobFlavour    = "longlunch"

queue
