executable     = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/compare_gpu.sh
output         = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/compare.$(ClusterId).out
error          = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/compare.$(ClusterId).err
log            = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/compare.$(ClusterId).log

request_cpus   = 2
request_memory = 8GB
request_gpus   = 0

+JobFlavour    = "espresso"

queue
