executable     = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/interpret_gpu.sh
output         = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/interpret.$(ClusterId).out
error          = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/interpret.$(ClusterId).err
log            = /eos/home-t/theofil/work/akcolor/makefriends/C/testAUC/logs/interpret.$(ClusterId).log

request_cpus   = 2
request_memory = 16GB
request_gpus   = 1

+JobFlavour    = "longlunch"

queue
